#SPDX-License-Identifier: MIT-0
---
# tasks file for postgresql
- name: install packages for postgresql
  apt:
    name: 
      - python3-psycopg2
      - postgresql 
    state: present
    update_cache: yes

- name: create db user
  become_user: postgres
  postgresql_user:
    name: "{{ mw_db_user }}"
    password: "{{ mw_db_password }}"

- name: create db
  become_user: postgres
  postgresql_db:
    name: "{{ mw_db_name }}"
    owner: "{{ mw_db_user }}"

- name: Allow remote connections to postgres
  lineinfile:
    path: /etc/postgresql/14/main/postgresql.conf
    regexp: "^#?listen_addresses ="
    line: "listen_addresses = '*'"
  notify: restart postgresql

- name: Copy pg_hba.conf
  template:
    src: pg_hba.conf.j2
    dest: /etc/postgresql/14/main/pg_hba.conf
    owner: postgres
    group: postgres
    mode: '0640'
  notify: restart postgresql

- name: handlers to restart postgres
  meta: flush_handlers
