---
- name: web_backup
  hosts: web_servers
  vars:
    web_backup_file: "/tmp/mw_web_backup_{{ ansible_date_time.date }}.tar.zst"
  tasks:
    - name: create archive
      archive:
        path: /var/www/mediawiki
        dest: "{{ web_backup_file }}"
        format: zstd

    - name: copy on ansible master host
      fetch:
        src: "{{ web_backup_file }}"
        dest: "/backups/wiki/{{ inventory_hostname }}_{{ ansible_date_time.date }}.tar.zst"
        flat: yes

    - name: remove file
      file:
        path: "{{ web_backup_file }}"
        state: absent


- name: pg_dump
  hosts: mw_db
  vars: 
    db_backup_file: "/tmp/mw_db_backup_{{ ansible_date_time.date }}.sql"
  tasks:
    - name: postgresqk pg_dump
      postgresql_db:
        become_user: postgres
        state: dump
        name: "{{ mwdb_name }}"
        target: "{{ db_backup_file }}"

    - name: copy on ansible master host
      fetch:
        src: "{{ db_backup_file }}"
        dest: "/backups/db/{{ inventory_hostname }}_{{ ansible_date_time.date }}.sql"
        flat: yes

    - name: remove file
      file:
        path: "{{ db_backup_file }}"
        state: absent
