---
- name: db for mediawiki
  host: mwdb_servers
  roles:
    - bootstrap
    - mw_db
    
- name: setup mediaWiki
  hosts: web_servers
  roles:
    - bootstrap
    - mw_packages
    - mw_nginx
    - mw_web

