#SPDX-License-Identifier: MIT-0
---
- name: install nginx
  apt:
   name: nginx
   state: present
   update_cache: yes

- name: remove default config
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: copy mediawiki config
  template:
    src: "{{ item }}"
    dest: /etc/nginx/sites-available/"{{ item }}"
    mode: "0644"
  loop:
    - mediawiki.conf.j2
    - zabbix.conf.j2
  notify: restart nginx

- name: add symlink
  file:
    src: /etc/nginx/sites-available/"{{ item }}"
    path: /etc/nginx/sites-enabled/"{{ item }}"
    state: link
  loop:
    - mediawiki.conf.j2
    - zabbix.conf.j2
  notify: restart nginx

- name: start nginx
  service:
    name: nginx
    enabled: yes
    state: started