#SPDX-License-Identifier: MIT-0
---
# tasks file for mw_db_replica
- name: install packages for postgresql
  apt:
    name: 
      - python3-psycopg2
      - postgresql 
    state: present
    update_cache: yes

- name: stop postgresql
  service:
    name: postgresql
    state: stopped

- name: Allow remote connections to postgres
  lineinfile:
    path: /etc/postgresql/14/main/postgresql.conf
    regexp: "^#?{{ item.key }} ="
    line: "{{ item.key }}='{{ item.value }}'"
  loop:
    - { key: "listen_addresses", value: "*" }
    - { key: "wal_level", value: "replica" }
    - { key: "archive_mode", value: "on" }
    - { key: "max_wal_senders", value: "8" }
    - { key: "hot_standby", value: "on" }

- name: remove default
  file:
    path: /var/lib/postgresql/14/main
    state: absent

- name: add new
  file:
    path: /var/lib/postgresql/14/main
    state: directory
    owner: postgres
    group: postgres
    mode: "0700"


- name: backup master database to replica
  become_user: postgres
  shell: |
    pg_basebackup -h {{ hostvars['mw-db-master']['ansible_host'] }} -D /var/lib/postgresql/14/main -U postgres -P -R -X stream

- name: start postgres
  service:
    name: postgresql
    state: started