dev:
  children: 
#-------------WEB_SERVERS_GROUP-----------------
    web_servers: 
      hosts: 
        mediawiki:
          ansible_host: 111.88.250.108
          internal_ip:  10.10.10.8
          db_host: 10.10.10.8

    lb_servers:
      hosts:
        nginx-lb:
          ansible_host: 111.88.242.183
          internal_ip:  10.10.10.17
      #-------ZABBIX_GROUP----------- 



  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/yandex_key 
    connection_protocol: ssh
    ansible_become: true 